### ISSUE TITLE
mws-connect or peddler

### ISSUE THREAD

**Issue by mtylty** [wombat/amazon_integration#2]
I've noticed there are both the [mws-connect](http://rubygems.org/gems/mws-connect) and the [peddler](http://rubygems.org/gems/peddler) gems required in the Gemfile.

Which one is the one that needs to be used? I presume peddler which looks like a much more advanced  and refined gem.

What about the current state of the test suite? It seems everything is maked as pending...

**Comment by JDutil** [comment]
It uses both as each serve their own purpose, and better tests need to be written.
